// source: jasper/vault/v1/query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
var cosmos_base_query_v1beta1_pagination_pb = require('../../../cosmos/base/query/v1beta1/pagination_pb.js');
goog.object.extend(proto, cosmos_base_query_v1beta1_pagination_pb);
var jasper_vault_v1_genesis_pb = require('../../../jasper/vault/v1/genesis_pb.js');
goog.object.extend(proto, jasper_vault_v1_genesis_pb);
var jasper_vault_v1_vault_pb = require('../../../jasper/vault/v1/vault_pb.js');
goog.object.extend(proto, jasper_vault_v1_vault_pb);
var google_api_annotations_pb = require('../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.jasper.vault.v1.PostSignedOptionPriceRequest', null, global);
goog.exportSymbol('proto.jasper.vault.v1.PostSignedOptionPricesRequest', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QueryPublicKeyPairsRequest', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QueryPublicKeyPairsResponse', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPaymentRequest', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPaymentResponse', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPriceRequest', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPriceResponse', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPricesRequest', null, global);
goog.exportSymbol('proto.jasper.vault.v1.QuerySignedOptionPricesResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.QueryPublicKeyPairsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QueryPublicKeyPairsRequest.displayName = 'proto.jasper.vault.v1.QueryPublicKeyPairsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jasper.vault.v1.QueryPublicKeyPairsResponse.repeatedFields_, null);
};
goog.inherits(proto.jasper.vault.v1.QueryPublicKeyPairsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QueryPublicKeyPairsResponse.displayName = 'proto.jasper.vault.v1.QueryPublicKeyPairsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.repeatedFields_, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPaymentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPaymentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPaymentResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPaymentResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPricesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPricesRequest.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPricesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jasper.vault.v1.QuerySignedOptionPricesResponse.repeatedFields_, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPricesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPricesResponse.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPricesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPriceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPriceRequest.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPriceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.QuerySignedOptionPriceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.QuerySignedOptionPriceResponse.displayName = 'proto.jasper.vault.v1.QuerySignedOptionPriceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jasper.vault.v1.PostSignedOptionPricesRequest.repeatedFields_, null);
};
goog.inherits(proto.jasper.vault.v1.PostSignedOptionPricesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.PostSignedOptionPricesRequest.displayName = 'proto.jasper.vault.v1.PostSignedOptionPricesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jasper.vault.v1.PostSignedOptionPriceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jasper.vault.v1.PostSignedOptionPriceRequest.displayName = 'proto.jasper.vault.v1.PostSignedOptionPriceRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QueryPublicKeyPairsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QueryPublicKeyPairsRequest;
  return proto.jasper.vault.v1.QueryPublicKeyPairsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageRequest;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QueryPublicKeyPairsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.query.v1beta1.PageRequest pagination = 1;
 * @return {?proto.cosmos.base.query.v1beta1.PageRequest}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageRequest} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageRequest, 1));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageRequest|undefined} value
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} returns this
*/
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} returns this
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsRequest.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QueryPublicKeyPairsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    publicKeyNodeIdPairList: jspb.Message.toObjectList(msg.getPublicKeyNodeIdPairList(),
    jasper_vault_v1_vault_pb.PublicKeyNodeIdPair.toObject, includeInstance),
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QueryPublicKeyPairsResponse;
  return proto.jasper.vault.v1.QueryPublicKeyPairsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new jasper_vault_v1_vault_pb.PublicKeyNodeIdPair;
      reader.readMessage(value,jasper_vault_v1_vault_pb.PublicKeyNodeIdPair.deserializeBinaryFromReader);
      msg.addPublicKeyNodeIdPair(value);
      break;
    case 2:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageResponse;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageResponse.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QueryPublicKeyPairsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPublicKeyNodeIdPairList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      jasper_vault_v1_vault_pb.PublicKeyNodeIdPair.serializeBinaryToWriter
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PublicKeyNodeIdPair public_key_node_id_pair = 1;
 * @return {!Array<!proto.jasper.vault.v1.PublicKeyNodeIdPair>}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.getPublicKeyNodeIdPairList = function() {
  return /** @type{!Array<!proto.jasper.vault.v1.PublicKeyNodeIdPair>} */ (
    jspb.Message.getRepeatedWrapperField(this, jasper_vault_v1_vault_pb.PublicKeyNodeIdPair, 1));
};


/**
 * @param {!Array<!proto.jasper.vault.v1.PublicKeyNodeIdPair>} value
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse} returns this
*/
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.setPublicKeyNodeIdPairList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jasper.vault.v1.PublicKeyNodeIdPair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jasper.vault.v1.PublicKeyNodeIdPair}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.addPublicKeyNodeIdPair = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jasper.vault.v1.PublicKeyNodeIdPair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse} returns this
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.clearPublicKeyNodeIdPairList = function() {
  return this.setPublicKeyNodeIdPairList([]);
};


/**
 * optional cosmos.base.query.v1beta1.PageResponse pagination = 2;
 * @return {?proto.cosmos.base.query.v1beta1.PageResponse}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageResponse} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageResponse, 2));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageResponse|undefined} value
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse} returns this
*/
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QueryPublicKeyPairsResponse} returns this
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QueryPublicKeyPairsResponse.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest;
  return proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageRequest;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.query.v1beta1.PageRequest pagination = 1;
 * @return {?proto.cosmos.base.query.v1beta1.PageRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageRequest} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageRequest, 1));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageRequest|undefined} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    signedOptionPaymentList: jspb.Message.toObjectList(msg.getSignedOptionPaymentList(),
    jasper_vault_v1_vault_pb.SignOptionPayment.toObject, includeInstance),
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse;
  return proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new jasper_vault_v1_vault_pb.SignOptionPayment;
      reader.readMessage(value,jasper_vault_v1_vault_pb.SignOptionPayment.deserializeBinaryFromReader);
      msg.addSignedOptionPayment(value);
      break;
    case 2:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageResponse;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageResponse.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSignedOptionPaymentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      jasper_vault_v1_vault_pb.SignOptionPayment.serializeBinaryToWriter
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SignOptionPayment signed_option_payment = 1;
 * @return {!Array<!proto.jasper.vault.v1.SignOptionPayment>}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.getSignedOptionPaymentList = function() {
  return /** @type{!Array<!proto.jasper.vault.v1.SignOptionPayment>} */ (
    jspb.Message.getRepeatedWrapperField(this, jasper_vault_v1_vault_pb.SignOptionPayment, 1));
};


/**
 * @param {!Array<!proto.jasper.vault.v1.SignOptionPayment>} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.setSignedOptionPaymentList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jasper.vault.v1.SignOptionPayment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jasper.vault.v1.SignOptionPayment}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.addSignedOptionPayment = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jasper.vault.v1.SignOptionPayment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.clearSignedOptionPaymentList = function() {
  return this.setSignedOptionPaymentList([]);
};


/**
 * optional cosmos.base.query.v1beta1.PageResponse pagination = 2;
 * @return {?proto.cosmos.base.query.v1beta1.PageResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageResponse} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageResponse, 2));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageResponse|undefined} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    proofs: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPaymentRequest;
  return proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProofs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProofs();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string proofs = 1;
 * @return {string}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.prototype.getProofs = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentRequest.prototype.setProofs = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    signedOptionPayment: (f = msg.getSignedOptionPayment()) && jasper_vault_v1_vault_pb.SignOptionPayment.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPaymentResponse;
  return proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new jasper_vault_v1_vault_pb.SignOptionPayment;
      reader.readMessage(value,jasper_vault_v1_vault_pb.SignOptionPayment.deserializeBinaryFromReader);
      msg.setSignedOptionPayment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSignedOptionPayment();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      jasper_vault_v1_vault_pb.SignOptionPayment.serializeBinaryToWriter
    );
  }
};


/**
 * optional SignOptionPayment signed_option_payment = 1;
 * @return {?proto.jasper.vault.v1.SignOptionPayment}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.prototype.getSignedOptionPayment = function() {
  return /** @type{?proto.jasper.vault.v1.SignOptionPayment} */ (
    jspb.Message.getWrapperField(this, jasper_vault_v1_vault_pb.SignOptionPayment, 1));
};


/**
 * @param {?proto.jasper.vault.v1.SignOptionPayment|undefined} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.prototype.setSignedOptionPayment = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.prototype.clearSignedOptionPayment = function() {
  return this.setSignedOptionPayment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.prototype.hasSignedOptionPayment = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPricesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPricesRequest;
  return proto.jasper.vault.v1.QuerySignedOptionPricesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageRequest;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPricesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.query.v1beta1.PageRequest pagination = 1;
 * @return {?proto.cosmos.base.query.v1beta1.PageRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageRequest} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageRequest, 1));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageRequest|undefined} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesRequest.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPricesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    signedoptionpriceList: jspb.Message.toObjectList(msg.getSignedoptionpriceList(),
    jasper_vault_v1_vault_pb.SignOptionPrices.toObject, includeInstance),
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPricesResponse;
  return proto.jasper.vault.v1.QuerySignedOptionPricesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new jasper_vault_v1_vault_pb.SignOptionPrices;
      reader.readMessage(value,jasper_vault_v1_vault_pb.SignOptionPrices.deserializeBinaryFromReader);
      msg.addSignedoptionprice(value);
      break;
    case 2:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageResponse;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageResponse.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPricesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSignedoptionpriceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      jasper_vault_v1_vault_pb.SignOptionPrices.serializeBinaryToWriter
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SignOptionPrices signedOptionPrice = 1;
 * @return {!Array<!proto.jasper.vault.v1.SignOptionPrices>}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.getSignedoptionpriceList = function() {
  return /** @type{!Array<!proto.jasper.vault.v1.SignOptionPrices>} */ (
    jspb.Message.getRepeatedWrapperField(this, jasper_vault_v1_vault_pb.SignOptionPrices, 1));
};


/**
 * @param {!Array<!proto.jasper.vault.v1.SignOptionPrices>} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.setSignedoptionpriceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jasper.vault.v1.SignOptionPrices=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jasper.vault.v1.SignOptionPrices}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.addSignedoptionprice = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jasper.vault.v1.SignOptionPrices, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.clearSignedoptionpriceList = function() {
  return this.setSignedoptionpriceList([]);
};


/**
 * optional cosmos.base.query.v1beta1.PageResponse pagination = 2;
 * @return {?proto.cosmos.base.query.v1beta1.PageResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageResponse} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageResponse, 2));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageResponse|undefined} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPricesResponse} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QuerySignedOptionPricesResponse.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPriceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    optionasset: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPriceRequest;
  return proto.jasper.vault.v1.QuerySignedOptionPriceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOptionasset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPriceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOptionasset();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string optionAsset = 1;
 * @return {string}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.prototype.getOptionasset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPriceRequest.prototype.setOptionasset = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.QuerySignedOptionPriceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    signedoptionprice: (f = msg.getSignedoptionprice()) && jasper_vault_v1_vault_pb.SignOptionPrices.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPriceResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.QuerySignedOptionPriceResponse;
  return proto.jasper.vault.v1.QuerySignedOptionPriceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPriceResponse}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new jasper_vault_v1_vault_pb.SignOptionPrices;
      reader.readMessage(value,jasper_vault_v1_vault_pb.SignOptionPrices.deserializeBinaryFromReader);
      msg.setSignedoptionprice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.QuerySignedOptionPriceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSignedoptionprice();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      jasper_vault_v1_vault_pb.SignOptionPrices.serializeBinaryToWriter
    );
  }
};


/**
 * optional SignOptionPrices signedOptionPrice = 1;
 * @return {?proto.jasper.vault.v1.SignOptionPrices}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.prototype.getSignedoptionprice = function() {
  return /** @type{?proto.jasper.vault.v1.SignOptionPrices} */ (
    jspb.Message.getWrapperField(this, jasper_vault_v1_vault_pb.SignOptionPrices, 1));
};


/**
 * @param {?proto.jasper.vault.v1.SignOptionPrices|undefined} value
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPriceResponse} returns this
*/
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.prototype.setSignedoptionprice = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jasper.vault.v1.QuerySignedOptionPriceResponse} returns this
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.prototype.clearSignedoptionprice = function() {
  return this.setSignedoptionprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.QuerySignedOptionPriceResponse.prototype.hasSignedoptionprice = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.PostSignedOptionPricesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    paramsList: jspb.Message.toObjectList(msg.getParamsList(),
    proto.jasper.vault.v1.PostSignedOptionPriceRequest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.PostSignedOptionPricesRequest}
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.PostSignedOptionPricesRequest;
  return proto.jasper.vault.v1.PostSignedOptionPricesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.PostSignedOptionPricesRequest}
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.jasper.vault.v1.PostSignedOptionPriceRequest;
      reader.readMessage(value,proto.jasper.vault.v1.PostSignedOptionPriceRequest.deserializeBinaryFromReader);
      msg.addParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.PostSignedOptionPricesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.jasper.vault.v1.PostSignedOptionPriceRequest.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PostSignedOptionPriceRequest params = 1;
 * @return {!Array<!proto.jasper.vault.v1.PostSignedOptionPriceRequest>}
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.prototype.getParamsList = function() {
  return /** @type{!Array<!proto.jasper.vault.v1.PostSignedOptionPriceRequest>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jasper.vault.v1.PostSignedOptionPriceRequest, 1));
};


/**
 * @param {!Array<!proto.jasper.vault.v1.PostSignedOptionPriceRequest>} value
 * @return {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} returns this
*/
proto.jasper.vault.v1.PostSignedOptionPricesRequest.prototype.setParamsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jasper.vault.v1.PostSignedOptionPriceRequest=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest}
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.prototype.addParams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jasper.vault.v1.PostSignedOptionPriceRequest, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} returns this
 */
proto.jasper.vault.v1.PostSignedOptionPricesRequest.prototype.clearParamsList = function() {
  return this.setParamsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jasper.vault.v1.PostSignedOptionPriceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    optionasset: jspb.Message.getFieldWithDefault(msg, 1, ""),
    strikeprice: jspb.Message.getFieldWithDefault(msg, 2, 0),
    expiredate: jspb.Message.getFieldWithDefault(msg, 3, 0),
    optiontype: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jasper.vault.v1.PostSignedOptionPriceRequest;
  return proto.jasper.vault.v1.PostSignedOptionPriceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOptionasset(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStrikeprice(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setExpiredate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOptiontype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jasper.vault.v1.PostSignedOptionPriceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOptionasset();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStrikeprice();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getExpiredate();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * optional string optionAsset = 1;
 * @return {string}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.getOptionasset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} returns this
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.setOptionasset = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 strikePrice = 2;
 * @return {number}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.getStrikeprice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} returns this
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.setStrikeprice = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 expireDate = 3;
 * @return {number}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.getExpiredate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} returns this
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.setExpiredate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 optionType = 4;
 * @return {number}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.getOptiontype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} returns this
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.setOptiontype = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jasper.vault.v1.PostSignedOptionPriceRequest} returns this
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.clearOptiontype = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jasper.vault.v1.PostSignedOptionPriceRequest.prototype.hasOptiontype = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.jasper.vault.v1);
