/**
 * @fileoverview gRPC-Web generated client stub for jasper.vault.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: jasper/vault/v1/query.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js')

var cosmos_base_query_v1beta1_pagination_pb = require('../../../cosmos/base/query/v1beta1/pagination_pb.js')

var jasper_vault_v1_genesis_pb = require('../../../jasper/vault/v1/genesis_pb.js')

var jasper_vault_v1_vault_pb = require('../../../jasper/vault/v1/vault_pb.js')

var google_api_annotations_pb = require('../../../google/api/annotations_pb.js')

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js')
const proto = {};
proto.jasper = {};
proto.jasper.vault = {};
proto.jasper.vault.v1 = require('./query_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.jasper.vault.v1.QueryClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.jasper.vault.v1.QueryPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jasper.vault.v1.QueryPublicKeyPairsRequest,
 *   !proto.jasper.vault.v1.QueryPublicKeyPairsResponse>}
 */
const methodDescriptor_Query_PublicKeyPairs = new grpc.web.MethodDescriptor(
  '/jasper.vault.v1.Query/PublicKeyPairs',
  grpc.web.MethodType.UNARY,
  proto.jasper.vault.v1.QueryPublicKeyPairsRequest,
  proto.jasper.vault.v1.QueryPublicKeyPairsResponse,
  /**
   * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jasper.vault.v1.QueryPublicKeyPairsResponse.deserializeBinary
);


/**
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jasper.vault.v1.QueryPublicKeyPairsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jasper.vault.v1.QueryPublicKeyPairsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jasper.vault.v1.QueryClient.prototype.publicKeyPairs =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jasper.vault.v1.Query/PublicKeyPairs',
      request,
      metadata || {},
      methodDescriptor_Query_PublicKeyPairs,
      callback);
};


/**
 * @param {!proto.jasper.vault.v1.QueryPublicKeyPairsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jasper.vault.v1.QueryPublicKeyPairsResponse>}
 *     Promise that resolves to the response
 */
proto.jasper.vault.v1.QueryPromiseClient.prototype.publicKeyPairs =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jasper.vault.v1.Query/PublicKeyPairs',
      request,
      metadata || {},
      methodDescriptor_Query_PublicKeyPairs);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest,
 *   !proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse>}
 */
const methodDescriptor_Query_SignedOptionPayments = new grpc.web.MethodDescriptor(
  '/jasper.vault.v1.Query/SignedOptionPayments',
  grpc.web.MethodType.UNARY,
  proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest,
  proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse,
  /**
   * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse.deserializeBinary
);


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jasper.vault.v1.QueryClient.prototype.signedOptionPayments =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPayments',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPayments,
      callback);
};


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jasper.vault.v1.QuerySignedOptionPaymentsResponse>}
 *     Promise that resolves to the response
 */
proto.jasper.vault.v1.QueryPromiseClient.prototype.signedOptionPayments =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPayments',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPayments);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jasper.vault.v1.QuerySignedOptionPaymentRequest,
 *   !proto.jasper.vault.v1.QuerySignedOptionPaymentResponse>}
 */
const methodDescriptor_Query_SignedOptionPayment = new grpc.web.MethodDescriptor(
  '/jasper.vault.v1.Query/SignedOptionPayment',
  grpc.web.MethodType.UNARY,
  proto.jasper.vault.v1.QuerySignedOptionPaymentRequest,
  proto.jasper.vault.v1.QuerySignedOptionPaymentResponse,
  /**
   * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jasper.vault.v1.QuerySignedOptionPaymentResponse.deserializeBinary
);


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jasper.vault.v1.QuerySignedOptionPaymentResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jasper.vault.v1.QueryClient.prototype.signedOptionPayment =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPayment',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPayment,
      callback);
};


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPaymentRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jasper.vault.v1.QuerySignedOptionPaymentResponse>}
 *     Promise that resolves to the response
 */
proto.jasper.vault.v1.QueryPromiseClient.prototype.signedOptionPayment =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPayment',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPayment);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jasper.vault.v1.QuerySignedOptionPricesRequest,
 *   !proto.jasper.vault.v1.QuerySignedOptionPricesResponse>}
 */
const methodDescriptor_Query_SignedOptionPrices = new grpc.web.MethodDescriptor(
  '/jasper.vault.v1.Query/SignedOptionPrices',
  grpc.web.MethodType.UNARY,
  proto.jasper.vault.v1.QuerySignedOptionPricesRequest,
  proto.jasper.vault.v1.QuerySignedOptionPricesResponse,
  /**
   * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jasper.vault.v1.QuerySignedOptionPricesResponse.deserializeBinary
);


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jasper.vault.v1.QuerySignedOptionPricesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jasper.vault.v1.QuerySignedOptionPricesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jasper.vault.v1.QueryClient.prototype.signedOptionPrices =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPrices',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPrices,
      callback);
};


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPricesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jasper.vault.v1.QuerySignedOptionPricesResponse>}
 *     Promise that resolves to the response
 */
proto.jasper.vault.v1.QueryPromiseClient.prototype.signedOptionPrices =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPrices',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPrices);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jasper.vault.v1.QuerySignedOptionPriceRequest,
 *   !proto.jasper.vault.v1.QuerySignedOptionPriceResponse>}
 */
const methodDescriptor_Query_SignedOptionPrice = new grpc.web.MethodDescriptor(
  '/jasper.vault.v1.Query/SignedOptionPrice',
  grpc.web.MethodType.UNARY,
  proto.jasper.vault.v1.QuerySignedOptionPriceRequest,
  proto.jasper.vault.v1.QuerySignedOptionPriceResponse,
  /**
   * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jasper.vault.v1.QuerySignedOptionPriceResponse.deserializeBinary
);


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jasper.vault.v1.QuerySignedOptionPriceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jasper.vault.v1.QuerySignedOptionPriceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jasper.vault.v1.QueryClient.prototype.signedOptionPrice =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPrice',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPrice,
      callback);
};


/**
 * @param {!proto.jasper.vault.v1.QuerySignedOptionPriceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jasper.vault.v1.QuerySignedOptionPriceResponse>}
 *     Promise that resolves to the response
 */
proto.jasper.vault.v1.QueryPromiseClient.prototype.signedOptionPrice =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPrice',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPrice);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jasper.vault.v1.PostSignedOptionPricesRequest,
 *   !proto.jasper.vault.v1.QuerySignedOptionPriceResponse>}
 */
const methodDescriptor_Query_SignedOptionPriceByParams = new grpc.web.MethodDescriptor(
  '/jasper.vault.v1.Query/SignedOptionPriceByParams',
  grpc.web.MethodType.UNARY,
  proto.jasper.vault.v1.PostSignedOptionPricesRequest,
  proto.jasper.vault.v1.QuerySignedOptionPriceResponse,
  /**
   * @param {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jasper.vault.v1.QuerySignedOptionPriceResponse.deserializeBinary
);


/**
 * @param {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jasper.vault.v1.QuerySignedOptionPriceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jasper.vault.v1.QuerySignedOptionPriceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jasper.vault.v1.QueryClient.prototype.signedOptionPriceByParams =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPriceByParams',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPriceByParams,
      callback);
};


/**
 * @param {!proto.jasper.vault.v1.PostSignedOptionPricesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jasper.vault.v1.QuerySignedOptionPriceResponse>}
 *     Promise that resolves to the response
 */
proto.jasper.vault.v1.QueryPromiseClient.prototype.signedOptionPriceByParams =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jasper.vault.v1.Query/SignedOptionPriceByParams',
      request,
      metadata || {},
      methodDescriptor_Query_SignedOptionPriceByParams);
};


module.exports = proto.jasper.vault.v1;

